config/routes.rb
Rails.application.routes.draw do
  root 'pages#main'
  resources :wishes
end

app/models/wish.rb
class Wish < ActiveRecord::Base
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def main
  end

end

app/controllers/wishes_controller.rb
class WishesController < ApplicationController
  
  def index
    @wishes = Wish.all
  end
  
  def show
    @wish = Wish.find(params[:id])
  end
  
  def new
    @wish = Wish.new
  end

  def edit
    @wish = Wish.find(params[:id])
  end
  
  def create
    @wish = Wish.new(wish_params)
    if @wish.save
      redirect_to @wish, notice: 'Wish was successfully created.'
    else
      render :new
    end
  end
  
  def update
    @wish = Wish.find(params[:id])
    if @wish.update(wish_params)
      redirect_to @wish, notice: 'Wish was successfully updated.'
    else
      render :edit
    end
  end
  
  def destroy
    @wish = Wish.find(params[:id])
    @wish.destroy
    redirect_to wishes_url, notice: 'Wish was successfully destroyed.'
  end

  private
  
  def wish_params
    params.require(:wish).permit(:title, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/wishes_helper.rb
module WishesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wishlist</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <header>
      <h1>Wishlist</h1>
    </header>
    <%= yield %>
  </div>
</body>
</html>

app/views/pages/main.html.erb
<p>Welcome to the Wishlist</p>

<%= link_to 'See the list', wishes_path, class: 'button' %>

app/views/wishes/_form.html.erb
<%= form_for(@wish) do |f| %>
  <% if @wish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wish.errors.count, "error") %> prohibited this wish from being saved:</h2>

      <ul>
      <% @wish.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, placeholder: "Your wonderful wish" %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description, placeholder: "Its wonderful description" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wishes/edit.html.erb
<h1>Editing Your Wish</h1>

<%= render 'form' %>

<div class="buttons">
  <%= link_to 'Show', @wish, class: 'button secondary' %> 
  <%= link_to 'Back', wishes_path, class: 'button secondary' %>
</div>

app/views/wishes/index.html.erb
<% if flash[:notice] %>
<div class="notice"><%= flash[:notice] %></div>
<% end %>

<ol class="wishes">
  <% @wishes.each do |wish| %>
  <li class="wish"><%= link_to wish.title, wish %></li>
  <% end %>
</ol>

<div class="buttons"><%= link_to 'New Wish', new_wish_path, class: 'button secondary' %></div>

app/views/wishes/new.html.erb
<h1>New Wish</h1>

<%= render 'form' %>

<div class="buttons">
  <%= link_to 'Back', wishes_path, class: 'button secondary' %>
</div>

app/views/wishes/show.html.erb
<% if flash[:notice] %>
<div class="notice"><%= flash[:notice] %></div>
<% end %>

<h2 class="wish-title"><%= @wish.title %></h2>

<p class="wish-description"><%= @wish.description %></p>

<div class="buttons">
<%= link_to 'Back', wishes_path, class: 'button secondary' %>
<%= link_to 'Edit', edit_wish_path(@wish), class: 'button secondary' %>
<%= link_to 'Remove', @wish, method: 'delete', class: 'button secondary' %>
</div>